BOT_TOKEN = ""
TOPGG_TOKEN = ""
TOPGG_AUTH = ""
GOOGLE_API_TOKEN = ""
OR_API_TOKEN = ""
WAIFUIM_TOKEN = ""
WEATHER_API = ""
TENOR_API_TOKEN = ""
VOTE_WEBHOOK = ""
ERROR_WEBHOOK = ""
LOG_WEBHOOK = ""
GUILDS_WEBHOOK = ""
REPORT_WEBHOOK = ""
BOT_NEWS = ""

[LAVALINK]
identifier = ""
uri = ""
password = ""
