CREATE TABLE IF NOT EXISTS songs (
    id BIGINT PRIMARY KEY NOT NULL, -- Generated by Oi
    identifier TEXT NOT NULL, -- Provided by Lavalink
    uri TEXT NOT NULL,
    encoded TEXT NOT NULL,
    source TEXT NOT NULL,
    title TEXT NOT NULL,
    artist TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS playlists (
    id BIGINT PRIMARY KEY NOT NULL,
    author BIGINT NOT NULL,
    name TEXT NOT NULL,
    image TEXT,
    UNIQUE (name, author)
);

CREATE TABLE IF NOT EXISTS playlist_songs (
    playlist_id BIGINT NOT NULL,
    song_id BIGINT NOT NULL,
    position INT NOT NULL, -- Order of the song in the playlist
    FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE,
    FOREIGN KEY (song_id) REFERENCES songs(id) ON DELETE CASCADE,
    PRIMARY KEY (playlist_id, song_id) -- Ensures a song can only appear once per playlist
);

